# Generated by Django 5.2.7 on 2025-10-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie'), ('BREAK_START', 'Début pause'), ('BREAK_END', 'Fin pause')], max_length=20, verbose_name='Type de pointage')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('date', models.DateField(auto_now_add=True, db_index=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes/Commentaires')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'db_table': 'attendances',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_check_in_time', models.TimeField(default='09:00', verbose_name="Heure d'arrivée attendue")),
                ('expected_check_out_time', models.TimeField(default='17:00', verbose_name='Heure de départ attendue')),
                ('tolerance_minutes', models.IntegerField(default=15, verbose_name='Tolérance (minutes)')),
                ('notify_missing_check_in', models.BooleanField(default=True, verbose_name='Notifier entrée manquante')),
                ('notify_missing_check_out', models.BooleanField(default=True, verbose_name='Notifier sortie manquante')),
                ('notify_manager', models.BooleanField(default=True, verbose_name='Notifier le manager')),
            ],
            options={
                'verbose_name': 'Paramètre de pointage',
                'verbose_name_plural': 'Paramètres de pointage',
                'db_table': 'attendance_settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MISSING_CHECK_IN', "Pointage d'entrée manquant"), ('MISSING_CHECK_OUT', 'Pointage de sortie manquant'), ('LATE_CHECK_IN', "Retard à l'entrée"), ('EARLY_CHECK_OUT', 'Sortie anticipée'), ('VALIDATION_REQUIRED', 'Validation requise'), ('VALIDATION_APPROVED', 'Pointage validé'), ('VALIDATION_REJECTED', 'Pointage rejeté')], max_length=30, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Durée totale')),
                ('break_duration', models.DurationField(blank=True, null=True, verbose_name='Durée des pauses')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Session complète')),
            ],
            options={
                'verbose_name': 'Session de travail',
                'verbose_name_plural': 'Sessions de travail',
                'db_table': 'work_sessions',
                'ordering': ['-date'],
            },
        ),
    ]
