# Generated by Django 5.2.7 on 2025-10-23 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='users.team', verbose_name='Équipe'),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='attendance.attendance', verbose_name='Pointage concerné'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='check_in',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_check_in', to='attendance.attendance', verbose_name='Pointage entrée'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='check_out',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_check_out', to='attendance.attendance', verbose_name='Pointage sortie'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', 'date'], name='attendances_user_id_e63f54_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'attendance_type'], name='attendances_date_4d99af_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
    ]
