# Generated by Django 4.2.11 on 2025-10-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "Employé"),
                    ("manager", "Manager"),
                    ("admin", "Administrateur"),
                ],
                default="employee",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="function",
            field=models.CharField(blank=True, max_length=50, verbose_name="Fonction"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Téléphone"
            ),
        ),
    ]
